/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8f6dee1d-56f5-49a0-913a-6b16da9c2392",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dEYvOyCeJ",
    "aws_user_pools_web_client_id": "sid3ofehs775vr5divrg44bjs",
    "oauth": {
        "domain": "m8iykpfptfad-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d3hi9mzn0coe5y.amplifyapp.com/login",
        "redirectSignOut": "https://main.d3hi9mzn0coe5y.amplifyapp.com/login",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://i2clieojxjfy5daw6ll5uy453a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bf5d6ukafnhztgvwxuw2wx5onq",
    "aws_user_files_s3_bucket": "jacksofalltrades212f85e205a64dde82391216b940ac9163942-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
