import React from "react";
import {
  useAuth,
  useNavigateAction,
  useStateMutationAction,
} from "@aws-amplify/ui-react/internal";
import { Image, Flex, Text, View, Icon } from "@aws-amplify/ui-react";
import { CgProfile } from "@react-icons/all-files/cg/CgProfile";
import { IconContext } from "@react-icons/all-files/lib";

export default function TopBarFinal() {
  //pulls  user info in order to display the email
  const authAttributes = useAuth().user?.attributes ?? {};

  //redirection links to take the user to the correct url on the website when clicked by the user
  const homeOnClick = useNavigateAction({ type: "url", url: "/" });
  const aboutOnClick = useNavigateAction({ type: "url", url: "/about" });
  const skillOnClick = useNavigateAction({ type: "url", url: "/skilllist" });
  const suggestOnClick = useNavigateAction({ type: "url", url: "/suggest" });
  const settingsOnClick = useNavigateAction({ type: "url", url: "/settings" });
  
  //taskbar graphics
  return (
    <Flex
      className="topbar"
      display="flex"
      gap="20px"
      direction="row"
      width="100vw"
      height="80px"
      justifyContent="space-between"
      alignItems="center"
      paddingLeft="0px"
      flex='none'
      order="0"
      alignSelf="stretch"
      flexGrow="0"
      
    >
      <Flex>
      
      <Flex
        //this flex group is our logo generated by text and blocks
        //it was created by designing it in figma and generating the code

        width="48px"
        height="68.79px"
        flex='none'
        order="0"
        flexGrow="0"
        
      >
        <View
          //icon built with 3 rectangles and 2 J
          width="29px"
          height="43px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="4px"
          left="25.54px"
          transformOrigin="top left"
          transform="rotate(30.98deg)"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(220,220,220,1)"
          border=".5px SOLID rgba(0,0,0,.5)"
        ></View>
        <View
          width="29px"
          height="43px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="12px"
          left="26.14px"
          transformOrigin="top left"
          transform="rotate(30.98deg)"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(242,236,236,1)"
          border=".5px SOLID rgba(0,0,0,.5)"
        ></View>
        <View
          width="29px"
          height="43px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="21px"
          left="27.14px"
          transformOrigin="top left"
          transform="rotate(30.98deg)"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,250,250,1)"
          border=".5px SOLID rgba(0,0,0,.5)"
        ></View>
        <Text
          fontFamily="Inter"
          fontSize="12px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="18px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="30px"
          left="44.88px"
          transformOrigin="top left"
          transform="rotate(33.29deg)"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="J"
        ></Text>
        <Text
          fontFamily="Inter"
          fontSize="12px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="18px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="45px"
          left="14.88px"
          transformOrigin="top left"
          transform="rotate(33.29deg)"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="J"
        ></Text>
      </Flex>
      <Flex
        //left side of the top bar
        display="flex"
        direction="row"
        alignItems="center"
        justifyContent="flex-start"
        paddingLeft="0px"
        gap="30px"
        width="55vw"
        height="unset"
        flex="none"
        order="1"
        alignSelf="stretch"
        flexGrow="1"
      >
        
        <text
          className="textlink"
          children="Home"
          flex="none"
          order="0"
          flexGrow="0"
          //changes color of Home and redirects the user to the home page
          onClick={() => {
            homeOnClick();

          }}
        ></text>
        <text
          className="textlink"
          fontFamily="Inter"
          fontSize="16px"
          fontWeight="400"
          lineHeight="24px"
          textAlign="left"
          letterSpacing="0.01px"
          children="About"
          flex="none"
          order="1"
          flexGrow="0"
          //changes color of about and redirects the user to the about page
          
          onClick={() => {
            aboutOnClick();

          }}
          
        ></text>
        <text
          className="textlink"
          children="Skill List"
          flex="none"
          order="2"
          flexGrow="0"
          //tedirects the user to the skill page
          onClick={() => {
            skillOnClick();
          }}
        ></text>
        <text
          //this page does not exist (but we wanted to be able to implement it)
          className="textlink"
          children="Suggest a Skill"
          flex="none"
          order="3"
          flexGrow="0"
          //changes color of calender  and redirects the user to the calener page
          onClick={() => {
            suggestOnClick();
          }}
        ></text>
        
      </Flex>
      </Flex>
      <Flex
        //right side of the task bar
        display="flex"
        paddingRight="15px"
        direction="row"
        width="34vw"
        height="unset"
        justifyContent="flex-end"
        alignItems="center"
        flex="none"
        order="2"
        alignSelf="stretch"
        flexGrow="1"
      >
        <Flex
          display="flex"
          gap="15px"
          direction="row"
          width="30vw"
          height="unset"
          justifyContent="flex-end"
          alignItems="center"
          flex="none"
          order="0"
          flexGrow="0"
        >
          
          <Flex
            display="flex"
            gap="25px"
            direction="row"
            width="unset"
            height="unset"
            alignItems="center"
            justifyContent="flex-end"
            padding="0px"
            flex="none"
            order="1"
            flexGrow="0"
          >
            <div className="logo" >
            <IconContext.Provider value={{style:{fontSize: '35px'}}}>
              <CgProfile 
              ></CgProfile>
            </IconContext.Provider>
            </div>
              <text
                fontFamily="Inter"
                className="text"
                fontSize="16px"
                fontWeight="400"
                color="rgba(13,26,38,1)"
                lineHeight="24px"
                textAlign="left"
                display="flex"
                direction="row"             
                alignItems="center"
                //displays the logged in users email or nothing if the user is not logged in
                children={authAttributes["email"]}
                flex="none"
                order="0"
                flexGrow="0"
                
              ></text>  
              <text
              className="textlink"
              children="Settings"
              onClick={() => {
                settingsOnClick();
              }}
              >
              </text>         
          </Flex>
        </Flex>
      </Flex>
    </Flex>
  );
}
